Feature/unit test
UST-QuAntiL/nisq-analyzer pull request #19
Opened 2020-09-07 06:42 UTC by TimPhillip

#### Short Description
Adds Unit tests for the NISQ Analyzer.

#### Proposed Changes

  * ImplementationSelectionTest class contains unit tests checking the ability to select a suitable implementation 
  * SimulatorExecutionTest class executes some implementations with the IBMQ_QASM_SIMULATOR qpu and checks the returns. 

**Fixes**: #

2020-09-22 10:04 UTC, salmma commented on org.planqk.nisq.analyzer.core/src/main/java/org/planqk/nisq/analyzer/core/knowledge/prolog/PrologQueryEngine.java
> +            if (!param.matches("-?\\s*[0-9]+\\.?[0-9]*"))
Does not work if input is a binary **string**, e.g. 0110. NISQ Analyzer interprets it as an integer

2020-09-24 06:28 UTC, salmma requested changes
fix regex handling for Strings

2020-10-07 20:01 UTC, salmma commented on org.planqk.nisq.analyzer.core/src/main/java/org/planqk/nisq/analyzer/core/knowledge/prolog/PrologQueryEngine.java
> +            if (!param.matches("-?\\s*[0-9]+\\.?[0-9]*"))
should be deleted!

2020-10-07 20:03 UTC, salmma requested changes
Delete old adjustements for inserting '

2021-03-26 12:02 UTC, closed without merging

2021-03-26 12:03 UTC, TimPhillip commented
Replaced by #37, because requirements changed over time